# Generated by Django 4.2.19 on 2025-02-25 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-sort_order', 'tag_name'], 'permissions': [('can_manage_tags', 'Can manage tags'), ('can_view_inactive_tags', 'Can view inactive tags')], 'verbose_name': '话术标签', 'verbose_name_plural': '话术标签'},
        ),
        migrations.AddField(
            model_name='tag',
            name='created_by',
            field=models.ForeignKey(help_text='创建该标签的用户', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tags', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='tag',
            name='description',
            field=models.TextField(blank=True, help_text='标签的详细描述', verbose_name='标签描述'),
        ),
        migrations.AddField(
            model_name='tag',
            name='is_active',
            field=models.BooleanField(default=True, help_text='标签是否可用', verbose_name='是否启用'),
        ),
        migrations.AddField(
            model_name='tag',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='父标签，用于构建标签层级关系', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='tags.tag', verbose_name='父标签'),
        ),
        migrations.AddField(
            model_name='tag',
            name='sort_order',
            field=models.IntegerField(default=0, help_text='标签的排序权重，数字越大越靠前', verbose_name='排序'),
        ),
        migrations.AddField(
            model_name='tag',
            name='updated_by',
            field=models.ForeignKey(help_text='最后更新该标签的用户', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_tags', to=settings.AUTH_USER_MODEL, verbose_name='更新者'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='标签创建的时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_name',
            field=models.CharField(error_messages={'unique': '该标签名称已存在'}, help_text='标签的名称，必须唯一', max_length=50, unique=True, verbose_name='标签名称'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='标签最后更新的时间', verbose_name='更新时间'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['tag_name'], name='tag_name_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['sort_order'], name='sort_order_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['is_active'], name='is_active_idx'),
        ),
    ]
