# Generated by Django 4.2.19 on 2025-02-25 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone_number'], name='users_user_phone_n_7fe504_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['name'], name='users_user_name_7f8296_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['start_date', 'end_date'], name='users_user_start_d_b3f344_idx'),
        ),
    ]
