# Generated by Django 4.2.19 on 2025-02-25 06:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_users_user_phone_n_7fe504_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'permissions': [('can_view_user_list', 'Can view user list'), ('can_export_users', 'Can export users'), ('can_manage_user_validity', 'Can manage user validity period')], 'verbose_name': '前端用户', 'verbose_name_plural': '前端用户'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='phone_number_idx',
            old_name='users_user_phone_n_7fe504_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='name_idx',
            old_name='users_user_name_7f8296_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='validity_period_idx',
            old_name='users_user_start_d_b3f344_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='用户创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_by',
            field=models.ForeignKey(help_text='创建该用户的管理员', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL, verbose_name='创建用户'),
        ),
        migrations.AlterField(
            model_name='user',
            name='end_date',
            field=models.DateField(help_text='账号有效期结束日期', verbose_name='有效期结束日期'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(help_text='用户姓名', max_length=50, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(help_text='用户手机号，用于登录', max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='请输入有效的11位手机号', regex='^1[3-9]\\d{9}$')], verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='start_date',
            field=models.DateField(help_text='账号有效期开始日期', verbose_name='有效期开始日期'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='用户最后更新时间', verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_by',
            field=models.ForeignKey(help_text='最后更新该用户的管理员', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_users', to=settings.AUTH_USER_MODEL, verbose_name='更新用户'),
        ),
    ]
