# Generated by Django 4.2.19 on 2025-02-25 08:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(error_messages={'unique': '该手机号已被注册'}, help_text='用户手机号，用于登录', max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='请输入有效的11位手机号', regex='^1[3-9]\\d{9}$')], verbose_name='手机号'),
        ),
    ]
