# Generated by Django 4.2.19 on 2025-02-24 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='话术内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '话术',
                'verbose_name_plural': '话术',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScriptTagRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scripts.script', verbose_name='话术')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tags.tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '话术-标签关联',
                'verbose_name_plural': '话术-标签关联',
            },
        ),
        migrations.AddField(
            model_name='script',
            name='tags',
            field=models.ManyToManyField(related_name='scripts', through='scripts.ScriptTagRelation', to='tags.tag', verbose_name='话术标签'),
        ),
    ]
