# Generated by Django 4.2.19 on 2025-02-24 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scripts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
        migrations.AlterUniqueTogether(
            name='scripttagrelation',
            unique_together={('script', 'tag')},
        ),
    ]
