# Generated by Django 4.2.19 on 2025-02-25 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_alter_tag_options_tag_created_by_tag_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scripts', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='script',
            options={'ordering': ['-sort_order', '-updated_at'], 'permissions': [('can_manage_scripts', 'Can manage scripts'), ('can_view_inactive_scripts', 'Can view inactive scripts')], 'verbose_name': '话术', 'verbose_name_plural': '话术'},
        ),
        migrations.AlterModelOptions(
            name='scripttagrelation',
            options={'ordering': ['-created_at'], 'verbose_name': '话术标签关联', 'verbose_name_plural': '话术标签关联'},
        ),
        migrations.RemoveField(
            model_name='script',
            name='user',
        ),
        migrations.AddField(
            model_name='script',
            name='created_by',
            field=models.ForeignKey(help_text='创建该话术的用户', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_scripts', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='script',
            name='is_active',
            field=models.BooleanField(default=True, help_text='话术是否可用', verbose_name='是否启用'),
        ),
        migrations.AddField(
            model_name='script',
            name='script_type',
            field=models.CharField(choices=[('opening', '开场白'), ('closing', '结束语'), ('qa', '问答'), ('custom', '自定义')], default='custom', help_text='话术类型', max_length=20, verbose_name='类型'),
        ),
        migrations.AddField(
            model_name='script',
            name='sort_order',
            field=models.IntegerField(default=0, help_text='话术的排序权重，数字越大越靠前', verbose_name='排序'),
        ),
        migrations.AddField(
            model_name='script',
            name='title',
            field=models.CharField(default='未命名话术', help_text='话术标题', max_length=100, verbose_name='标题'),
        ),
        migrations.AddField(
            model_name='script',
            name='updated_by',
            field=models.ForeignKey(help_text='最后更新该话术的用户', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_scripts', to=settings.AUTH_USER_MODEL, verbose_name='更新者'),
        ),
        migrations.AddField(
            model_name='script',
            name='version',
            field=models.IntegerField(default=1, help_text='话术版本号', verbose_name='版本号'),
        ),
        migrations.AddField(
            model_name='scripttagrelation',
            name='created_by',
            field=models.ForeignKey(help_text='创建该关联的用户', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_script_tag_relations', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='scripttagrelation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='关联最后更新时间', verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='scripttagrelation',
            name='updated_by',
            field=models.ForeignKey(help_text='最后更新该关联的用户', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_script_tag_relations', to=settings.AUTH_USER_MODEL, verbose_name='更新者'),
        ),
        migrations.AlterField(
            model_name='script',
            name='content',
            field=models.TextField(help_text='话术内容', verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='script',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='话术创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='script',
            name='tags',
            field=models.ManyToManyField(help_text='关联的标签', through='scripts.ScriptTagRelation', to='tags.tag', verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='script',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='话术最后更新时间', verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='scripttagrelation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='关联创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='scripttagrelation',
            name='script',
            field=models.ForeignKey(help_text='关联的话术', on_delete=django.db.models.deletion.CASCADE, to='scripts.script', verbose_name='话术'),
        ),
        migrations.AlterField(
            model_name='scripttagrelation',
            name='tag',
            field=models.ForeignKey(help_text='关联的标签', on_delete=django.db.models.deletion.CASCADE, to='tags.tag', verbose_name='标签'),
        ),
        migrations.AddIndex(
            model_name='script',
            index=models.Index(fields=['title'], name='script_title_idx'),
        ),
        migrations.AddIndex(
            model_name='script',
            index=models.Index(fields=['script_type'], name='script_type_idx'),
        ),
        migrations.AddIndex(
            model_name='script',
            index=models.Index(fields=['is_active'], name='script_active_idx'),
        ),
        migrations.AddIndex(
            model_name='script',
            index=models.Index(fields=['sort_order'], name='script_order_idx'),
        ),
        migrations.AddIndex(
            model_name='scripttagrelation',
            index=models.Index(fields=['script', 'tag'], name='script_tag_idx'),
        ),
    ]
