# Generated by Django 4.2.19 on 2025-02-25 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tags', '0002_alter_tag_options_tag_created_by_tag_description_and_more'),
        ('scripts', '0003_alter_script_options_alter_scripttagrelation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='script',
            options={'ordering': ['-updated_at'], 'verbose_name': '话术', 'verbose_name_plural': '话术'},
        ),
        migrations.RemoveIndex(
            model_name='script',
            name='script_title_idx',
        ),
        migrations.RemoveIndex(
            model_name='script',
            name='script_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='script',
            name='script_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='script',
            name='script_order_idx',
        ),
        migrations.RemoveIndex(
            model_name='scripttagrelation',
            name='script_tag_idx',
        ),
        migrations.AlterField(
            model_name='script',
            name='content',
            field=models.TextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='script',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='script',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_scripts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='script',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='script',
            name='script_type',
            field=models.CharField(choices=[('opening', '开场白'), ('closing', '结束语'), ('qa', '问答'), ('custom', '自定义')], max_length=20, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='script',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='script',
            name='tags',
            field=models.ManyToManyField(related_name='scripts', through='scripts.ScriptTagRelation', to='tags.tag', verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='script',
            name='title',
            field=models.CharField(max_length=100, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='script',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='script',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_scripts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='script',
            name='version',
            field=models.IntegerField(default=1, verbose_name='版本号'),
        ),
        migrations.AlterField(
            model_name='scripttagrelation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='scripttagrelation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_script_tag_relations', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='scripttagrelation',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='script_tag_relations', to='scripts.script', verbose_name='话术'),
        ),
        migrations.AlterField(
            model_name='scripttagrelation',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='script_tag_relations', to='tags.tag', verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='scripttagrelation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='scripttagrelation',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_script_tag_relations', to=settings.AUTH_USER_MODEL, verbose_name='更新者'),
        ),
        migrations.AlterModelTable(
            name='scripttagrelation',
            table='scripts_script_tags',
        ),
    ]
