# Generated by Django 4.2.19 on 2025-02-26 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0004_alter_script_options_remove_script_script_title_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='title',
            field=models.CharField(db_index=True, max_length=100, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='script',
            name='version',
            field=models.IntegerField(db_index=True, default=1, verbose_name='版本号'),
        ),
        migrations.AddIndex(
            model_name='script',
            index=models.Index(fields=['title', 'version'], name='script_title_ver_idx'),
        ),
        migrations.AddIndex(
            model_name='script',
            index=models.Index(fields=['title', '-version'], name='script_title_latest_idx'),
        ),
    ]
